export const NAVLINKS = [
  { title: "Home", href: "/home" },
  { title: "Live Matches", href: "/live-matches" },
  { title: "Portfolio", href: "/portfolio" },
  { title: "Contact", href: "/contact" },
  { title: "About Us", href: "/about-us" },
]

export const UNPROTECTED_ROUTES = [
  "/",
  "/login",
  "/terms-and-conditions",
  "/privacy-policy",
  "/about-us",
  "/about",
  "/contact",
  "/contact-us",
  "/game-rules",
  "/legality",
  "/referrals",
]

export const trends = [
  "Trending Now",
  "Fan Favorite",
  "High Stakes Series",
  "Must Watch",
  "Epic Clash",
  "Rivalry Reignited",
  "Season Highlight",
  "Explosive Matches",
  "Rematch Incoming",
  "Record Breaker",
  "Prime Time",
  "Top Teams Face Off",
  "Blockbuster Battle",
  "Thriller Ahead",
  "Game Changer",
  "Final Showdown",
  "Intense Rivalry",
  "Underdog Story",
  "Legends Return",
  "Historic Duel",
  "Edge of Seat",
  "Heart-Stopping",
  "Spectator’s Choice",
  "Can’t Miss Clash",
  "Ultimate Test",
  "Championship Fever",
  "Knockout Stage",
  "Surprise Outcome",
  "Title Decider",
  "Legacy Match",
];
